# Generated by Django 5.0.3 on 2024-03-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leather_world', '0003_user_idrestaurant_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.ForeignKey(db_column='area_pincode', default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leather_world.area'),
        ),
    ]
